server:
  port: 8081
spring:
  application:
    name: fed
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fed?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
  jackson:
    default-property-inclusion: non_null # JSON?????????
  data:
    redis:
      host: 192.168.191.137
      port: 6379
      lettuce:
        pool:
          max-active: 10
          max-idle: 10
          min-idle: 1
          time-between-eviction-runs: 10s
      database: 1
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    com: debug